server/config/routes.rb
Server::Application.routes.draw do

  root 'teams#profile'

  get 'admin' => 'admin#index'
  get 'team/:id' => 'teams#profile'
  get 'donations/thanks' => 'donations#thanks'
  resources :donations

  namespace :admin do
    resources :challenges
    resources :donations
    resources :incentives
    resources :users
    resources :teams
  end

  namespace :api do
    post 'user.:format' => 'users#create'
    get 'user.:format' => 'users#show'

    post 'donate.:format' => 'donations#create'
    get 'donations/for_donor.:format' => 'donations#show_for_donor'
    get 'donations/for_referrer.:format' => 'donations#show_for_referrer'

    get 'incentives.:format' => 'incentives#index'
    get 'incentive.:format' => 'incentives#show'
  end

end

server/app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class PhoneValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    value.scan /^\+(\d+)[ \-\(]+/
    prefix = $1
    international = prefix.to_s.rjust(3, '0')
    phone = value.gsub /^\+#{prefix}/, international
    phone = phone.gsub /[\s\-\(\)]/, ''
    unless value =~ /^\d{8,20}$/i
      record.errors[attribute] << (options[:message] || "is not a phone number")
    end
  end
end

class User < ActiveRecord::Base
  has_many :teams
  has_many :referrals, :foreign_key => :referrer_id, :class_name => 'Donation'
  has_many :donations, :foreign_key => :donor_id
  has_many :challenges

  has_and_belongs_to_many :teams

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, uniqueness: true, email: true, allow_nil: true
  validates :phone, phone: true, allow_nil: true
  validate :phone_or_email_set

  def total_referrals
    self.referrals.inject(0.0) {|sum, d| d.value + sum }
  end

  def total_donations
    self.donations.inject(0.0) {|sum, d| d.value + sum }
  end

  def has_contact_info?
    has_email? || has_phone?
  end

  def has_email?
    !email.blank?
  end

  def has_phone?
    !phone.blank?
  end

  def has_teams?
    teams.any?
  end

  def as_json(options)
    result = super({
      :only => [:id, :name, :email, :phone]
    }.merge(options))
    result = result.reject { |a,b| b.nil? }
    result
  end

  private
  def phone_or_email_set
    if email.blank? && phone.blank?
      errors[:base] << "Email or Phone must be provided"
    end
  end
end

server/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :find_contextual_user, :except => [:index]
  before_filter :find_teams, :except => [:index]

  def create
    if @user.save
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.all
  end

  def new
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :phone
    )
  end

  def find_contextual_user
    @user = if (id = params[:id]).present?
      User.find(id)
    elsif params[:user]
      User.new(user_params)
    else
      User.new
    end
  end

  def find_teams
    @teams = Team.all
  end
end

server/app/controllers/api/users_controller.rb
class Api::UsersController < ApiController

  def create
    if (@user = User.find_by_email(params[:email].downcase))
      render_user_json
    else
      @user = User.new(permitted_params)
      if @user.save
        render_user_json
      else
        respond_to do |format|
          format.json { render :json => { :errors => @user.errors.full_messages }, :status => 400 }
        end
      end
    end
  end

  def show
    @user = User.find(params[:id])
    render_user_json
  end

  private
  def render_user_json
    respond_to do |format|
      format.json { render :json => @user }
    end
  end

  def permitted_params
    params.permit(
      :name,
      :email,
      :phone
    )
  end
end

server/app/helpers/users_helper.rb
module UsersHelper
end

server/app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <fieldset>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>

    <%= f.collection_select(:team_ids, @teams, :id,:name)%>
  </fieldset>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', admin_users_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/users/edit.html.erb
<h1>Editing user</h1>
<%= render 'form' %>

server/app/views/admin/users/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th colspan="2"></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New', new_admin_user_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>

server/app/views/admin/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.has_contact_info? %>
<dl>
  <% if @user.has_email? %>
  <dt>Email</dt>
  <dd><%= @user.email %></dd>
  <% end %>
  <% if @user.has_phone? %>
  <dt>Phone</dt>
  <dd><%= @user.phone %></dd>
  <% end %>
</dl>
<% end %>

<% if @user.has_teams? %>
<h2>Team Memberships</h2>
<ul>
<% @user.teams.each do |team| %>
  <li><%= team.name %></li>
<% end %>
</ul>
<% end %>

<p><%= link_to 'Edit', edit_admin_user_path(@user) %> | <%= link_to 'Directory', admin_users_path %> | <%= link_to 'Admin', admin_path %></p>