server/config/routes.rb
Server::Application.routes.draw do

  root 'teams#profile'

  get 'admin' => 'admin#index'
  get 'team/:id' => 'teams#profile'
  get 'donations/thanks' => 'donations#thanks'
  resources :donations

  namespace :admin do
    resources :challenges
    resources :donations
    resources :incentives
    resources :users
    resources :teams
  end

  namespace :api do
    post 'user.:format' => 'users#create'
    get 'user.:format' => 'users#show'

    post 'donate.:format' => 'donations#create'
    get 'donations/for_donor.:format' => 'donations#show_for_donor'
    get 'donations/for_referrer.:format' => 'donations#show_for_referrer'

    get 'incentives.:format' => 'incentives#index'
    get 'incentive.:format' => 'incentives#show'
  end

end

server/app/models/incentive.rb
class Incentive < ActiveRecord::Base
  def as_json(options)
    result = super({
      :only => [:value, :description]
    }.merge(options))
    result = result.reject { |a,b| b.nil? }
    result
  end
end

server/app/controllers/admin/incentives_controller.rb
class Admin::IncentivesController < ApplicationController
  before_filter :find_contextual_incentive, :except => [:index]

  def create
    if @incentive.save
      redirect_to admin_incentives_path
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @incentives = Incentive.all
  end

  def new
  end

  def show
  end

  def update
    if @incentive.update(incentive_params)
      redirect_to admin_incentives_path
    else
      render 'edit'
    end
  end

  private
  def incentive_params
    params.require(:incentive).permit(
      :value,
      :description,
    )
  end

  def find_contextual_incentive
    @incentive = if (id = params[:id]).present?
      Incentive.find(id)
    elsif params[:incentive]
      Incentive.new(incentive_params)
    else
      Incentive.new
    end
  end
end

server/app/controllers/api/incentives_controller.rb
class Api::IncentivesController < ApiController
  def index
    @incentives = Incentive.all
    respond_to do |format|
      format.json { render :json => @incentives }
    end
  end

  def show
    @incentive = Incentive.find_by! value: params[:value]
    respond_to do |format|
      format.json { render :json => @incentive }
    end
  end
end

server/app/helpers/incentives_helper.rb
module IncentivesHelper
end

server/app/views/admin/incentives/_form.html.erb
<%= form_for [:admin, @incentive] do |f| %>
  <% if @incentive.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@incentive.errors.count, "error") %> prohibited this incentive from being saved:</h2>
    <ul>
    <% @incentive.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', admin_incentives_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/incentives/edit.html.erb
<h1>Editing incentive</h1>
<%= render 'form' %>

server/app/views/admin/incentives/index.html.erb
<table>
  <tr>
    <th>Value</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>

<% @incentives.each do |incentive| %>
  <tr>
    <td><%= incentive.value %></td>
    <td><%= incentive.description %></td>
    <td><%= link_to 'Show', admin_incentive_path(incentive) %></td>
    <td><%= link_to 'Edit', edit_admin_incentive_path(incentive) %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New', new_admin_incentive_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/incentives/new.html.erb
<h1>New incentive</h1>
<%= render 'form' %>

server/app/views/admin/incentives/show.html.erb
<p>
  <strong>Value:</strong>
  <%= @incentive.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @incentive.description %>
</p>

<p><%= link_to 'Edit', edit_admin_incentive_path(@incentive) %> | <%= link_to 'Directory', admin_incentives_path %> | <%= link_to 'Admin', admin_path %></p>