server/config/routes.rb
Server::Application.routes.draw do

  root 'teams#profile'

  get 'admin' => 'admin#index'
  get 'team/:id' => 'teams#profile'
  get 'donations/thanks' => 'donations#thanks'
  resources :donations

  namespace :admin do
    resources :challenges
    resources :donations
    resources :incentives
    resources :users
    resources :teams
  end

  namespace :api do
    post 'user.:format' => 'users#create'
    get 'user.:format' => 'users#show'

    post 'donate.:format' => 'donations#create'
    get 'donations/for_donor.:format' => 'donations#show_for_donor'
    get 'donations/for_referrer.:format' => 'donations#show_for_referrer'

    get 'incentives.:format' => 'incentives#index'
    get 'incentive.:format' => 'incentives#show'
  end

end

server/app/models/donation.rb
class Donation < ActiveRecord::Base
  before_save :default_values
  after_save :update_challenge_current_funds

  belongs_to :challenge
  belongs_to :donor, :class_name => 'User'
  belongs_to :referrer, :class_name => 'User'

  validates_presence_of :value, :message => ": oops, looks like you didn't tell me how much you were donating"
  validates_presence_of :donor, :message => ": i can't find anyone with that donor ID"
  validates_presence_of :referrer, :message => ": i can't find anyone with that referrer ID"
  validates_numericality_of :value, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 100000000, :message => ": please donate at least $1"

  def value
    read_attribute(:value).to_f
  end

  def as_json(options)
    result = super({
      :only => [:currency, :value],
      :include => {
        donor: { only: [:id, :name] },
        referrer: { only: [:id, :name] },
        challenge: { only: [:name, :target, :current] }
    }}.merge(options))

    result = result.reject { |k,v| v.nil? }
  end

  private
  def default_values
    (self.currency ||= 'USD').upcase
    self.challenge_id = 1
  end

  def update_challenge_current_funds
    Challenge.update_raised_funds(self.challenge_id, self.value)
  end
end

server/app/controllers/admin/donations_controller.rb
class Admin::DonationsController < ApplicationController

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)

    if @donation.save
      redirect_to admin_donations_path
    else
      render 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def update
    @donation = Donation.find(params[:id])

    if @donation.update(donation_params)
      redirect_to admin_donations_path
    else
      render 'edit'
    end
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def index
    @donations = Donation.all
  end

  private
  def donation_params
    params.require(:donation).permit(
      :currency,
      :value
    )
  end
end

server/app/controllers/api/donations_controller.rb
class Api::DonationsController < ApiController

  def create
    @donation = Donation.new(permitted_params)
    if @donation.save
      respond_to do |format|
        format.json { render :json => @donation }
      end
    else
      respond_to do |format|
        format.json { render :json => { :errors => @donation.errors.full_messages }, :status => 400 }
      end
    end
  end

  def show_for_donor
    @donations = Donation.where(donor_id: params[:id])
    render_donations
  end

  def show_for_referrer
    @donations = Donation.where(referrer_id: params[:id])
    render_donations
  end

  private
  def render_donations
    total = 0
    donors = []
    @donations.each do |d|
      total += d[:value].to_f
      donors << d[:donor_id]
    end

    respond_to do |format|
      format.json { render :json => {
        :total_value => total,
        :count => @donations.size,
        :unique_donors => donors.uniq.size,
        :donations => @donations
      }}
    end
  end

  def permitted_params
    params.permit(
      :donor_id,
      :referrer_id,
      :currency,
      :value,
      :transaction_id,
      :transaction_source_id
    )
  end
end

server/app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def welcome
  end

  def thanks
  end

  def new
    @user = User.find(1) # Hardcode to Allison
    @challenge = Challenge.find(1)
  end

  def create
    @user = User.find(1) # Hardcode to Allison
    @challenge = Challenge.find(1)
    @donor = User.create({:name => params[:cardholder], :email => params[:email] })
    Donation.create({:referrer_id => @user.id, :donor => @donor, :value => params[:amount]})
    redirect_to("/donations/thanks")
  end
end

server/app/helpers/donations_helper.rb
module DonationsHelper
end

server/app/views/admin/donations/_form.html.erb
<%= form_for [:admin, @donation] do |f| %>
  <% if @donation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
    <ul>
    <% @donation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </p>

  <p>
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', admin_donations_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/donations/edit.html.erb
<h1>Editing donation</h1>
<%= render 'form' %>

server/app/views/admin/donations/index.html.erb
<table>
  <tr>
    <th>Donor</th>
    <th>Referrer</th>
    <th>Currency</th>
    <th>Value</th>
    <th colspan="2"></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.donor.name %></td>
    <td><%= donation.referrer.name %></td>
    <td><%= donation.currency %></td>
    <td><%= donation.value %></td>
    <td><%= link_to 'Show', admin_donation_path(donation) %></td>
    <td><%= link_to 'Edit', edit_admin_donation_path(donation) %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New', new_admin_donation_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/donations/new.html.erb
<h1>New donation</h1>
<%= render 'form' %>

server/app/views/admin/donations/show.html.erb
<p>
  <strong>Currency:</strong>
  <%= @donation.currency %>
</p>

<p>
  <strong>Value:</strong>
  <%= @donation.value %>
</p>

<p><%= link_to 'Edit', edit_admin_donation_path(@challenge) %> | <%= link_to 'Directory', admin_donations_path %> | <%= link_to 'Admin', admin_path %></p>