server/config/routes.rb
Server::Application.routes.draw do

  root 'teams#profile'

  get 'admin' => 'admin#index'
  get 'team/:id' => 'teams#profile'
  get 'donations/thanks' => 'donations#thanks'
  resources :donations

  namespace :admin do
    resources :challenges
    resources :donations
    resources :incentives
    resources :users
    resources :teams
  end

  namespace :api do
    post 'user.:format' => 'users#create'
    get 'user.:format' => 'users#show'

    post 'donate.:format' => 'donations#create'
    get 'donations/for_donor.:format' => 'donations#show_for_donor'
    get 'donations/for_referrer.:format' => 'donations#show_for_referrer'

    get 'incentives.:format' => 'incentives#index'
    get 'incentive.:format' => 'incentives#show'
  end

end

server/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User'
  has_and_belongs_to_many :users
end

server/app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to admin_teams_path
    else
      render 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to admin_teams_path
    else
      render 'edit'
    end
  end

  def show
    @team = Team.find(params[:id])
  end

  def profile
    # Don't explode on missing team while in demo
    @team = Team.find_by_id(params[:id])
  end

  def index
    @teams = Team.all
  end

  private
  def team_params
    params.require(:team).permit(
      :name
    )
  end
end

server/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def profile
    # Don't explode on missing team while in demo
    @team = Team.find(1)
    @challenge = Challenge.find(1)

    @donations = Donation.where(challenge_id: @challenge.id).sort_by do |donation|
      if donation.donor.present?
        donation.donor.total_donations
      else
        0
      end
    end.reverse
    @donations = @donations[0..2]

    @user = @team.users.first # Shoud be Allison
  end
end

server/app/helpers/teams_helper.rb
module TeamsHelper
end

server/app/views/admin/teams/_form.html.erb
<%= form_for [:admin, @team] do |f| %>
  <% if @team.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@team.errors.count, "error") %> prohibited this team from being saved:</h2>
    <ul>
    <% @team.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', admin_teams_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/teams/edit.html.erb
<h1>Editing team</h1>
<%= render 'form' %>

server/app/views/admin/teams/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th colspan="2"></th>
  </tr>

<% @teams.each do |team| %>
  <tr>
    <td><%= team.name %></td>
    <td><%= link_to 'Show', admin_team_path(team) %></td>
    <td><%= link_to 'Edit', edit_admin_team_path(team) %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New', new_admin_team_path %> | <%= link_to 'Admin', admin_path %></p>

server/app/views/admin/teams/new.html.erb
<h1>New team</h1>
<%= render 'form' %>

server/app/views/admin/teams/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @team.name %>
</p>

<p><%= link_to 'Edit', edit_admin_team_path(@team) %> | <%= link_to 'Directory', admin_teams_path %> | <%= link_to 'Admin', admin_path %></p>